---
minio_server_release: "RELEASE.2020-04-10T03-34-42Z"
vault_minio_key: "{{ lookup('hashi_vault', 'secret=kv-2/data/wa/minio') }}"
minio_server_datadirs: [ "/opt/minio-data-1", "/opt/minio-data-2" ]
minio_server_addr: ":9009"
minio_server_cluster_nodes: [ "http://sg-wa-a.ua.int/opt/minio-data-1", "http://sg-wa-a.ua.int/opt/minio-data-2", "http://sg-wa-b.ua.int/opt/minio-data-1", "http://sg-wa-b.ua.int/opt/minio-data-2" ]
minio_install_client: false
minio_access_key: "{{ vault_minio_key.data.minio_access_key }}"
minio_secret_key: "{{ vault_minio_key.data.minio_secret_key }}"